# Generated by Django 2.2.4 on 2020-09-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wishapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_hash',
            field=models.CharField(default='email', max_length=60),
            preserve_default=False,
        ),
    ]
