# Generated by Django 2.2.4 on 2020-09-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wishapp', '0002_user_email_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_hash',
            field=models.CharField(default='email', max_length=60),
        ),
    ]
