# Generated by Django 2.2.4 on 2020-09-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wishapp', '0006_granted_wish_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='granted_wish',
            old_name='like',
            new_name='likes',
        ),
    ]
