# Generated by Django 2.2.4 on 2020-09-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wishapp', '0007_auto_20200922_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='granted_wish',
            name='likes',
        ),
        migrations.AddField(
            model_name='granted_wish',
            name='likes',
            field=models.ManyToManyField(related_name='post_likes', to='Wishapp.User'),
        ),
    ]
